# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1D6Vle-CsgZ69PRsLNgzRUR91sHvD1-oo
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

sns.set_theme (style='darkgrid')

df = pd.read_csv ("ligue-1.csv")
print (df.columns.tolist()) #ver o nome das colunas

coluna_clube = "club_name"
coluna_valor = "fee"

# Limpar a coluna 'fee' para convertê-la em formato numérico
def clean_fee(fee_str):
    if pd.isna(fee_str): # Tratar valores NaN
        return 0.0
    if isinstance(fee_str, str):
        fee_str = fee_str.replace('€', '').replace(',', '.').strip()

        # Lidar com 'Loan fee:' primeiro
        if fee_str.startswith('Loan fee:'):
            fee_str = fee_str.replace('Loan fee:', '').strip()

        if 'm' in fee_str:
            try:
                return float(fee_str.replace('m', '')) * 1_000_000
            except ValueError:
                return 0.0
        elif 'Th.' in fee_str:
            try:
                return float(fee_str.replace('Th.', '')) * 1_000
            except ValueError:
                return 0.0
        elif fee_str == 'free transfer' or fee_str == '?':
            return 0.0
        try:
            return float(fee_str)
        except ValueError:
            return 0.0 # Retorna 0 para outros valores de string não analisáveis
    return float(fee_str) # Se não for uma string nem NaN, tenta converter diretamente

df['fee_cleaned_numeric'] = df[coluna_valor].apply(clean_fee)

# Agrupar os gastos por clubes e calcular o gasto total
gastos_ligue1 = df.groupby(coluna_clube)['fee_cleaned_numeric'].sum().sort_values(ascending=False).head(10)

# Gerando o gráfico com o matplotlib
plt.figure (figsize = (10 , 6))
grafico = sns.barplot(x = gastos_ligue1.values / 1e6, y = gastos_ligue1.index, palette = "Blues_r")

plt.title ("Os 10 clubes que mais gastaram com transferências na Ligue 1")
plt.xlabel ("Total Gasto (em Milhões de Euros €)", fontsize  = 12)
plt.ylabel ("Clube", fontsize = 12) # Corrigido o typo 'fontsizee'
plt.show() # Adicionar plt.show() para exibir o gráfico

from google.colab import files

print("Por favor, faça o upload do arquivo ligue-1.csv:")
uploaded = files.upload()